name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  tofu:
    name: OpenTofu Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.2

      - name: OpenTofu Init
        run: tofu -chdir=tf-bootstrap init

      - name: OpenTofu Validate
        run: tofu -chdir=tf-bootstrap validate

      - name: OpenTofu Format Check
        run: tofu -chdir=tf-bootstrap fmt -check -recursive

      - name: OpenTofu Plan
        env:
          TF_VAR_github_org: ${{ vars.FWDAYS_GITHUB_ORG }}
          TF_VAR_github_repository: ${{ vars.FWDAYS_GITHUB_REPO }}
          TF_VAR_github_token: ${{ secrets.FWDAYS_GITHUB_TOKEN }}
        run: tofu -chdir=tf-bootstrap plan -no-color -out=tfplan

      - name: Save OpenTofu Plan Output to a File
        run: tofu -chdir=tf-bootstrap show -no-color tfplan > plan.txt

      - name: Save OpenTofu Plan
        id: get_tf_plan
        run: |
          {
            echo 'tf_plan_output<<EOF'
            cat plan.txt
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Comment PR with OpenTofu Plan output
        uses: actions/github-script@v7
        env:
          TF_PLAN_OUTPUT: ${{ steps.get_tf_plan.outputs.tf_plan_output }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.TF_PLAN_OUTPUT
            })

      - name: "Upload OpenTofu Plan"
        uses: actions/upload-artifact@v4
        with:
          name: tofu-plan
          path: tf-bootstrap/tfplan
