name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  tofu:
    name: OpenTofu Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.2

      - name: OpenTofu Init
        run: tofu -chdir=tf-bootstrap init

    #   - name: OpenTofu Validate
    #     run: tofu -chdir=tf-bootstrap validate

      - name: OpenTofu Validate
        uses: dflook/tofu-validate@v1
        with:
          path: tf-bootstrap

    #   - name: OpenTofu Format Check
    #     run: tofu -chdir=tf-bootstrap fmt -check -recursive

      - name: OpenTofu Format Check
        uses: dflook/tofu-fmt-check@v1
        with:
          path: tf-bootstrap

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: tf-bootstrap
          quiet: true
        #   soft_fail: true
          download_external_modules: false

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'config'
          scan-ref: tf-bootstrap
        #   scan-ref: ${{ github.workspace }}/tf-bootstrap
          hide-progress: true
        #   exit-code: '1'
          ignore-unfixed: false
          severity: 'CRITICAL,HIGH'

      - name: OpenTofu Plan
        env:
          TF_VAR_github_org: ${{ vars.FWDAYS_GITHUB_ORG }}
          TF_VAR_github_repository: ${{ vars.FWDAYS_GITHUB_REPO }}
          TF_VAR_github_token: ${{ secrets.FWDAYS_GITHUB_TOKEN }}
        run: tofu -chdir=tf-bootstrap plan -no-color -out=tfplan

      - name: Save OpenTofu Plan Output to a File
        run: tofu -chdir=tf-bootstrap show -no-color tfplan > plan.txt

      - name: Save OpenTofu Plan as GitHub output
        id: get_tf_plan
        run: |
          {
            echo 'tf_plan_output<<EOF'
            cat plan.txt
            echo EOF
          } >> "$GITHUB_OUTPUT"

    #   - name: Comment PR with Checkov result output
    #     uses: actions/github-script@v7
    #     # env:
    #     #   TF_PLAN_OUTPUT: ${{ steps.get_tf_plan.outputs.tf_plan_output }}
    #     with:
    #       script: |
    #         github.rest.issues.createComment({
    #           issue_number: context.issue.number,
    #           owner: context.repo.owner,
    #           repo: context.repo.repo,
    #           body: process.env.CHECKOV_RESULTS
    #         })

      - name: Comment PR with OpenTofu Plan output
        uses: actions/github-script@v7
        env:
          TF_PLAN_OUTPUT: ${{ steps.get_tf_plan.outputs.tf_plan_output }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.TF_PLAN_OUTPUT
            })

    #   - name: Comment PR with OpenTofu Plan output (using action)
    #     uses: borchero/terraform-plan-comment@v2
    #     with:
    #       token: ${{ github.token }}
    #       working-directory: tf-bootstrap
    #       planfile: plan.txt

      - name: "Upload OpenTofu Plan as Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: tofu-plan
          path: tf-bootstrap/tfplan

      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: weave-ai

      - name: Setup Golang
        uses: actions/setup-go@v5

      - name: Setup Kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.7

      - name: Run Flux validation script
        run: curl https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/scripts/validate.sh | bash